// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Comparer is an autogenerated mock type for the Comparer type
type Comparer struct {
	mock.Mock
}

// Compare provides a mock function with given fields: b
func (_m *Comparer) Compare(b interface{}) int {
	ret := _m.Called(b)

	var r0 int
	if rf, ok := ret.Get(0).(func(interface{}) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
