// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageStorer is an autogenerated mock type for the MessageStorer type
type MessageStorer struct {
	mock.Mock
}

// GetMessage provides a mock function with given fields: forValidator
func (_m *MessageStorer) GetMessage(forValidator string) string {
	ret := _m.Called(forValidator)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(forValidator)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StoreMessage provides a mock function with given fields: forValidator, msg
func (_m *MessageStorer) StoreMessage(forValidator string, msg string) {
	_m.Called(forValidator, msg)
}
