// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/rbell/gospecexpress/pkg/interfaces"
)

// QualifierBuilder is an autogenerated mock type for the QualifierBuilder type
type QualifierBuilder struct {
	mock.Mock
}

// RequiredField provides a mock function with given fields: fieldName
func (_m *QualifierBuilder) RequiredField(fieldName string) interfaces.ValidatorBuilder {
	ret := _m.Called(fieldName)

	var r0 interfaces.ValidatorBuilder
	if rf, ok := ret.Get(0).(func(string) interfaces.ValidatorBuilder); ok {
		r0 = rf(fieldName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ValidatorBuilder)
		}
	}

	return r0
}
