// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/rbell/gospecexpress/pkg/interfaces"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: thing, messageStore
func (_m *Validator) Validate(thing interface{}, messageStore interfaces.MessageStorer) error {
	ret := _m.Called(thing, messageStore)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interfaces.MessageStorer) error); ok {
		r0 = rf(thing, messageStore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
