// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/govalidate/pkg/interfaces"
)

// ValidatorBuilder is an autogenerated mock type for the ValidatorBuilder type
type ValidatorBuilder struct {
	mock.Mock
}

// MaxLength provides a mock function with given fields: len
func (_m *ValidatorBuilder) MaxLength(len int) interfaces.ValidatorBuilder {
	ret := _m.Called(len)

	var r0 interfaces.ValidatorBuilder
	if rf, ok := ret.Get(0).(func(int) interfaces.ValidatorBuilder); ok {
		r0 = rf(len)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ValidatorBuilder)
		}
	}

	return r0
}

// RequiredField provides a mock function with given fields: fieldName
func (_m *ValidatorBuilder) RequiredField(fieldName string) interfaces.ValidatorBuilder {
	ret := _m.Called(fieldName)

	var r0 interfaces.ValidatorBuilder
	if rf, ok := ret.Get(0).(func(string) interfaces.ValidatorBuilder); ok {
		r0 = rf(fieldName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ValidatorBuilder)
		}
	}

	return r0
}
