// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: thing
func (_m *Validator) Validate(thing interface{}) bool {
	ret := _m.Called(thing)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = rf(thing)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
