// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidatorContextGetter is an autogenerated mock type for the ValidatorContextGetter type
type ValidatorContextGetter struct {
	mock.Mock
}

// GetContextData provides a mock function with given fields:
func (_m *ValidatorContextGetter) GetContextData() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetFieldValue provides a mock function with given fields: fieldName
func (_m *ValidatorContextGetter) GetFieldValue(fieldName string) interface{} {
	ret := _m.Called(fieldName)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(fieldName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
