// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import interfaces "gitlab.com/govalidate/pkg/interfaces"
import mock "github.com/stretchr/testify/mock"

// ValidatorBuilder is an autogenerated mock type for the ValidatorBuilder type
type ValidatorBuilder struct {
	mock.Mock
}

// RequiredField provides a mock function with given fields: fieldName
func (_m *ValidatorBuilder) RequiredField(fieldName string) interfaces.ValidatorBuilder {
	ret := _m.Called(fieldName)

	var r0 interfaces.ValidatorBuilder
	if rf, ok := ret.Get(0).(func(string) interfaces.ValidatorBuilder); ok {
		r0 = rf(fieldName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ValidatorBuilder)
		}
	}

	return r0
}
