// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rbell/gospecexpress/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// FieldValidationExpression is an autogenerated mock type for the FieldValidationExpression type
type FieldValidationExpression struct {
	mock.Mock
}

// Execute provides a mock function with given fields: thing, ctx
func (_m *FieldValidationExpression) Execute(thing interface{}, ctx interfaces.FieldValidatorContextGetter) (error, error) {
	ret := _m.Called(thing, ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interfaces.FieldValidatorContextGetter) error); ok {
		r0 = rf(thing, ctx)
	} else {
		r0 = ret.Error(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, interfaces.FieldValidatorContextGetter) error); ok {
		r1 = rf(thing, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
