// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SpecificationScoper is an autogenerated mock type for the SpecificationScoper type
type SpecificationScoper struct {
	mock.Mock
}

// ExtendsDefaultSpecification provides a mock function with given fields:
func (_m *SpecificationScoper) ExtendsDefaultSpecification() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetScopeName provides a mock function with given fields:
func (_m *SpecificationScoper) GetScopeName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
