// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidateOption is an autogenerated mock type for the ValidateOption type
type ValidateOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: something, context
func (_m *ValidateOption) Execute(something interface{}, context map[string]interface{}) {
	_m.Called(something, context)
}
