// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidationPredicate is an autogenerated mock type for the ValidationPredicate type
type ValidationPredicate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: thing, contextData
func (_m *ValidationPredicate) Execute(thing interface{}, contextData map[string]interface{}) bool {
	ret := _m.Called(thing, contextData)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}) bool); ok {
		r0 = rf(thing, contextData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
