// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidationExpression is an autogenerated mock type for the ValidationExpression type
type ValidationExpression struct {
	mock.Mock
}

// Execute provides a mock function with given fields: thing, contextData
func (_m *ValidationExpression) Execute(thing interface{}, contextData map[string]interface{}) (error, error) {
	ret := _m.Called(thing, contextData)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}) error); ok {
		r0 = rf(thing, contextData)
	} else {
		r0 = ret.Error(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, map[string]interface{}) error); ok {
		r1 = rf(thing, contextData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
