// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rbell/gospecexpress/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// ValidatorOption is an autogenerated mock type for the ValidatorOption type
type ValidatorOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: v
func (_m *ValidatorOption) Execute(v interfaces.Validator) {
	_m.Called(v)
}
