// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rbell/gospecexpress/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// ValueFromContext is an autogenerated mock type for the ValueFromContext type
type ValueFromContext struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *ValueFromContext) Execute(ctx interfaces.ValidatorContextGetter) interface{} {
	ret := _m.Called(ctx)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interfaces.ValidatorContextGetter) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
