// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WarningSetter is an autogenerated mock type for the WarningSetter type
type WarningSetter struct {
	mock.Mock
}

// ValidateAsWarning provides a mock function with given fields:
func (_m *WarningSetter) ValidateAsWarning() {
	_m.Called()
}
